### ISSUE TITLE
No connection 

### ISSUE THREAD

**Issue by Neededchicken38** [leo60228/HueSaber#2]
I press the button on my hue bridge, then put my headset on and press sync hue. Nothing happens. Mod is not working no matter what.

**Comment by leo60228** [comment]
Please run Beat Saber with the `--verbose` argument and look for any HueSaber related error messages. In order to be detected automatically, your hub must be connected to a Philips Hue account, but you can also manually enter an IP address. Under UserData in your Beat Saber directory, create a ModPrefs folder if it doesn't exist already. In ModPrefs, create a HueSaber.ini file, and put the following in it:

```ini
[HueSaber]
overrideIP=1.2.3.4
```

Replace 1.2.3.4 with your bridge's IP address.

**Comment by leo60228** [comment]
Also, I'm not sure how long the timeout is on pressing the button; if possible, I'd recommend pressing the button with the headset on, immediately before syncing.

**Comment by leo60228** [comment]
I believe that this issue has been fixed with the reupload of 1.1.0. Please re-open it if this is not the case.
